<a href="https://colab.research.google.com/github/sitiaisyah14/Machine-Learning_2022/blob/main/J2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# KNN tanpa library Scikit-learn
import numpy as np
import matplotlib.pyplot as plt

x_train = np.array([[26,8],
                    [26,11],
                    [29,8],
                    [34,10],
                    [36,11],
                    [33,8],
                    [30,9],
                    [27,10],
                    [27,11],
                    [26,11],
                    [31,13],
                    [34,8]])

y_train = ['Go out','Go out','Go out','Stay at home','Stay at home','Go out', 'Go out','Go out','Go out','Go out', 'Stay at home', 'Go out']

In [ ]:
x_test = np.array([[30,10]])

# calculate euclidean distance
# temperatur=30, uv index=10
dis = np.sqrt(np.sum((x_train-x_test)**2, axis=1))
print(dis)

# nilai k = 3
nn_sort=dis.argsort()[:3]
print(nn_sort)
nn_decision = np.take(y_train,nn_sort)
print(nn_decision)

from collections import Counter
b = Counter(np.take(y_train,dis.argsort()[:3]))
b.most_common(1)[0][0]


[4.47213595 4.12310563 2.23606798 4.         6.08276253 3.60555128
 1.         3.         3.16227766 4.12310563 3.16227766 4.47213595]
[6 2 7]
['Go out' 'Go out' 'Go out']


'Go out'

In [ ]:
x_test = np.array([[28,13]])

# calculate euclidean distance
# temperatur=28, uv index=13
dis = np.sqrt(np.sum((x_train-x_test)**2, axis=1))
print(dis)

# nilai k = 3
nn_sort=dis.argsort()[:3]
print(nn_sort)
nn_decision = np.take(y_train,nn_sort)
print(nn_decision)

from collections import Counter
b = Counter(np.take(y_train,dis.argsort()[:3]))
b.most_common(1)[0][0]


[5.38516481 2.82842712 5.09901951 6.70820393 8.24621125 7.07106781
 4.47213595 3.16227766 2.23606798 2.82842712 3.         7.81024968]
[8 1 9]
['Go out' 'Go out' 'Go out']


'Go out'

In [ ]:
x_test = np.array([[29,9]])

# calculate euclidean distance
# temperatur=29, uv index=9
dis = np.sqrt(np.sum((x_train-x_test)**2, axis=1))
print(dis)

# nilai k = 3
nn_sort=dis.argsort()[:3]
print(nn_sort)
nn_decision = np.take(y_train,nn_sort)
print(nn_decision)

from collections import Counter
b = Counter(np.take(y_train,dis.argsort()[:3]))
b.most_common(1)[0][0]


[3.16227766 3.60555128 1.         5.09901951 7.28010989 4.12310563
 1.         2.23606798 2.82842712 3.60555128 4.47213595 5.09901951]
[2 6 7]
['Go out' 'Go out' 'Go out']


'Go out'

In [ ]:
x_test = np.array([[31,12]])

# calculate euclidean distance
# temperatur=31, uv index=12
dis = np.sqrt(np.sum((x_train-x_test)**2, axis=1))
print(dis)

# nilai k = 3
nn_sort=dis.argsort()[:3]
print(nn_sort)
nn_decision = np.take(y_train,nn_sort)
print(nn_decision)

from collections import Counter
b = Counter(np.take(y_train,dis.argsort()[:3]))
b.most_common(1)[0][0]


[6.40312424 5.09901951 4.47213595 3.60555128 5.09901951 4.47213595
 3.16227766 4.47213595 4.12310563 5.09901951 1.         5.        ]
[10  6  3]
['Stay at home' 'Go out' 'Stay at home']


'Stay at home'

In [ ]:
x_test = np.array([[27,8]])

# calculate euclidean distance
# temperatur=27, uv index=8
dis = np.sqrt(np.sum((x_train-x_test)**2, axis=1))
print(dis)

# nilai k = 3
nn_sort=dis.argsort()[:3]
print(nn_sort)
nn_decision = np.take(y_train,nn_sort)
print(nn_decision)

from collections import Counter
b = Counter(np.take(y_train,dis.argsort()[:3]))
b.most_common(1)[0][0]


[1.         3.16227766 2.         7.28010989 9.48683298 6.
 3.16227766 2.         3.         3.16227766 6.40312424 7.        ]
[0 2 7]
['Go out' 'Go out' 'Go out']


'Go out'

In [ ]:
# KNN menggunakan library Scikit-learn
from sklearn.preprocessing import LabelBinarizer
from sklearn.neighbors import KNeighborsClassifier

lb=LabelBinarizer()
y_trainbin = lb.fit_transform(y_train)
print(y_trainbin)

k=3

# temperatur=30, uv index=10
x_test = np.array([[30,10]])

clf=KNeighborsClassifier(n_neighbors=k)
clf.fit(x_train,y_trainbin.reshape(-1))
pred_bin = clf.predict(np.array([x_test]).reshape(1,-1))[0]
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

[[0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]
['Go out']


In [ ]:
lb=LabelBinarizer()
y_trainbin = lb.fit_transform(y_train)
print(y_trainbin)

k=3

# temperatur=28, uv index=13
x_test = np.array([[28,13]])

clf=KNeighborsClassifier(n_neighbors=k)
clf.fit(x_train,y_trainbin.reshape(-1))
pred_bin = clf.predict(np.array([x_test]).reshape(1,-1))[0]
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

[[0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]
['Go out']


In [ ]:
lb=LabelBinarizer()
y_trainbin = lb.fit_transform(y_train)
print(y_trainbin)

k=3

# temperatur=29, uv index=9
x_test = np.array([[29,9]])

clf=KNeighborsClassifier(n_neighbors=k)
clf.fit(x_train,y_trainbin.reshape(-1))
pred_bin = clf.predict(np.array([x_test]).reshape(1,-1))[0]
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

[[0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]
['Go out']


In [ ]:
lb=LabelBinarizer()
y_trainbin = lb.fit_transform(y_train)
print(y_trainbin)

k=3

# temperatur=31, uv index=12
x_test = np.array([[31,12]])

clf=KNeighborsClassifier(n_neighbors=k)
clf.fit(x_train,y_trainbin.reshape(-1))
pred_bin = clf.predict(np.array([x_test]).reshape(1,-1))[0]
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

[[0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]
['Stay at home']


In [ ]:
lb=LabelBinarizer()
y_trainbin = lb.fit_transform(y_train)
print(y_trainbin)

k=3

# temperatur=27, uv index=8
x_test = np.array([[27,8]])

clf=KNeighborsClassifier(n_neighbors=k)
clf.fit(x_train,y_trainbin.reshape(-1))
pred_bin = clf.predict(np.array([x_test]).reshape(1,-1))[0]
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)

[[0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]
['Go out']


In [ ]:
# evaluasi model

x_test = np.array([[30,10],
                  [28,13],
                  [29,9],
                  [31,12],
                  [27,8]
                  ])
y_test = ['Stay at home','Go out', 'Go out', 'Stay at home', 'Go out']

# Prediksi Sistem
lb=LabelBinarizer()
y_testbin = lb.fit_transform(y_test)
print('label biner:%s' %y_testbin.T[0])

k=3
clf=KNeighborsClassifier(n_neighbors=k)
clf.fit(x_train,y_trainbin.reshape(-1))
pred_bin = clf.predict(x_test)
pred_label = lb.inverse_transform(pred_bin)
print(pred_label)



label biner:[1 0 0 1 0]
['Go out' 'Go out' 'Go out' 'Stay at home' 'Go out']


In [ ]:
# # Akurasi
from sklearn.metrics import accuracy_score
print('akurasi : %s' % accuracy_score(y_testbin,pred_bin))

akurasi : 0.8


In [ ]:
# Presisi
from sklearn.metrics import precision_score
print('presisi: %s' % precision_score(y_testbin,pred_bin))

presisi: 1.0


In [ ]:
# Recall
from sklearn.metrics import recall_score
print('recall: %s' % recall_score(y_testbin,pred_bin))

recall: 0.5


In [ ]:
# Regresi menggunakan algoritma KNN

import matplotlib.pyplot as plt

x_train = np.array([[26,1],
                    [26,1],
                    [29,1],
                    [34,0],
                    [36,0],
                    [33,1],
                    [30,1],
                    [27,1],
                    [27,1],
                    [26,1],
                    [31,0],
                    [34,1]])

y_train = [8,11,8,10,11,8,9,10,11,11,13,8]

x_test = np.array([[30,0],
                  [28,1],
                  [29,1],
                  [31,0],
                  [27,1]
                  ])
y_test = [10,13,9,12,8]

from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

clf = KNeighborsRegressor(n_neighbors=k)
clf.fit(x_train,y_train)
predictions = clf.predict(x_test)
print('pediksi : %s' %predictions)
print('MAE : %s' % mean_absolute_error(y_test,predictions))
print('MSE : %s' % mean_squared_error(y_test,predictions))


pediksi : [10.          9.66666667  9.         10.         10.66666667]
MAE : 1.6
MSE : 4.444444444444445
